import { type RouteConfig, index, route, layout } from "@react-router/dev/routes";

export default [
  layout("routes/marketing-layout.tsx", [
    index("routes/home.tsx"),
    route("about", "routes/about.tsx"),
    route("contact", "routes/contact.tsx"),
    route("privacy", "routes/privacy.tsx"),
    route("terms", "routes/terms.tsx"),
    route("shipping", "routes/shipping.tsx"),
    route("refunds", "routes/refunds.tsx"),
    route("sourcing", "routes/sourcing.tsx"),
    route("social-responsibility", "routes/social-responsibility.tsx"),
    route("sites", "routes/sites.tsx"),
    route("shop", "routes/shop.tsx"),
    route("impressum", "routes/impressum.tsx"),
    route("policy-coffee-recipe-extension", "routes/policy-coffee-recipe-extension.tsx"),
    route("future-of-coffee", "routes/future-of-coffee.tsx"),
    route("products", "routes/products-redirect.ts"),

    route("coffee-farms-koraput", "routes/coffee-farms-koraput.tsx"),
    route("coffee-farms-near-bhubaneswar", "routes/coffee-farms-near-bhubaneswar.tsx"),
    route("coffee-farms-odisha", "routes/coffee-farms-odisha.tsx"),
    route("odisha-coffee-export", "routes/odisha-coffee-export.tsx"),
    route("odisha-coffee-varieties", "routes/odisha-coffee-varieties.tsx"),

    route("roasted-coffee", "routes/roasted-coffee.tsx"),
    route("roasted-coffee/:productSlug", "routes/roasted-coffee-productslug.tsx"),
    route("spices", "routes/spices.tsx"),
    route("farms", "routes/farms-index.tsx"),
    route("farms/:slug", "routes/farms-slug.tsx"),
    route("farms/:slug/green-coffee", "routes/farms-slug-green-coffee.tsx"),
    route("farms/:slug/roasted-coffee", "routes/farms-slug-roasted-coffee.tsx"),
    route("farms/:slug/products", "routes/farms-slug-products.tsx"),
    route("farms/:slug/products/:productSlug", "routes/farms-slug-products-productslug.tsx"),
    route("buy-green-beans", "routes/buy-green-beans-index.tsx"),
    route("buy-green-beans/:productSlug", "routes/buy-green-beans-productslug.tsx"),
    route("buy-coffee", "routes/buy-coffee-index.tsx"),
    route("buy-in", "routes/buy-in-index.tsx"),
    route("buy-in/:city", "routes/buy-in-city.tsx"),
    route("india/:state/green-coffee", "routes/india-state-green-coffee.tsx"),
    route("india/:state/:city/green-coffee", "routes/india-state-city-green-coffee.tsx"),
    route("buy-green-coffee", "routes/buy-green-coffee-index.tsx"),
    route("buy-green-coffee/:location", "routes/buy-green-coffee-location.tsx"),
    route("buy-roasted-coffee", "routes/buy-roasted-coffee-index.tsx"),
    route("buy-roasted-coffee/:location", "routes/buy-roasted-coffee-location.tsx"),
    route(":country/green-coffee", "routes/country-green-coffee.tsx"),
    route("reviews", "routes/reviews-index.tsx"),
    route("newsroom", "routes/newsroom-index.tsx"),
    route("newsroom/:slug", "routes/newsroom-slug.tsx"),
    route("guides", "routes/guides-index.tsx"),
    route("guides/:slug", "routes/guides-slug.tsx"),

    route("cart", "routes/cart.tsx"),
    route("checkout", "routes/checkout.tsx"),
    route("checkout/success", "routes/checkout-success.tsx"),
    route("o/:slug", "routes/o-slug.tsx"),
    route("order-builder", "routes/order-builder.tsx"),
  ]),

  // Resource routes — raw responses, no page chrome
  route("products.json", "routes/products-json.ts"),
  route("api/contact", "routes/api-contact.ts"),
  route("api/create-payment", "routes/create-payment.ts"),
  route("api/geo", "routes/geo.ts"),
  route("api/indexnow", "routes/api-indexnow.ts"),
  route("api/internal/orders", "routes/internal-orders.ts"),
  route("api/internal/orders/:id", "routes/internal-orders-id.ts"),
  route("api/reviews", "routes/reviews.ts"),
  route("api/reviews/upload-url", "routes/reviews-upload-url.ts"),
  route("api/reviews/verify-email", "routes/reviews-verify-email.ts"),
  route("api/webhooks/cashfree", "routes/api-webhooks-cashfree.ts"),
  route("api/webhooks/enterprise", "routes/api-webhooks-enterprise.ts"),
  route("api/webhooks/feedback", "routes/api-webhooks-feedback.ts"),
  route("api/webhooks/feature", "routes/api-webhooks-feature.ts"),
] satisfies RouteConfig;
