"use client";

import { use, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, PackageX } from "lucide-react";
import { useCart } from "@/context/cart-context";
import { decodeShareItems } from "@/lib/cart-share";

// Self-describing share link generated by the order builder's "Share This
// Order" button (see (marketing)/order-builder/page.tsx). The slug IS the
// cart - decoding it needs no database lookup. Visiting this page drops
// those items into the visitor's own cart (localStorage, via CartProvider)
// and sends them straight to /cart to review and check out.

export default function SharedOrderPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = use(params);
  const router = useRouter();
  const { add } = useCart();
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    const items = decodeShareItems(decodeURIComponent(slug));
    if (items.length === 0) {
      setFailed(true);
      return;
    }
    for (const item of items) {
      add(item.productId, item.weight, item.farmId);
    }
    router.replace("/cart");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [slug]);

  if (failed) {
    return (
      <div className="max-w-7xl mx-auto px-4 lg:px-6 py-24 text-center">
        <PackageX className="w-12 h-12 mx-auto text-odisha-black/20 mb-4" />
        <h1 className="font-serif text-2xl font-bold text-odisha-black mb-2">This order link isn&apos;t valid</h1>
        <p className="text-odisha-black/50 text-sm">
          It may be malformed or reference a product that no longer exists.
        </p>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-4 lg:px-6 py-24 flex flex-col items-center justify-center gap-3 text-odisha-black/40">
      <Loader2 className="w-6 h-6 animate-spin" />
      <p className="text-sm">Loading shared order…</p>
    </div>
  );
}
