import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router";
import { Loader2, PackageX } from "lucide-react";
import { useCart } from "@/context/cart-context";
import { decodeShareItems } from "@/lib/cart-share";

// Self-describing share link generated by the order builder's "Share This
// Order" button (see routes/order-builder.tsx). The slug IS the cart -
// decoding it needs no database lookup. Visiting this page drops those
// items into the visitor's own cart (localStorage, via CartProvider) and
// sends them straight to /cart to review and check out.

export default function SharedOrderPage() {
  const { slug } = useParams<{ slug: string }>();
  const navigate = useNavigate();
  const { add } = useCart();
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    if (!slug) return;
    const items = decodeShareItems(decodeURIComponent(slug));
    if (items.length === 0) {
      setFailed(true);
      return;
    }
    for (const item of items) {
      add(item.productId, item.weight, item.farmId);
    }
    navigate("/cart", { replace: true });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [slug]);

  if (failed) {
    return (
      <div className="max-w-7xl mx-auto px-4 lg:px-6 py-24 text-center">
        <PackageX className="w-12 h-12 mx-auto text-odisha-black/20 mb-4" />
        <h1 className="font-serif text-2xl font-bold text-odisha-black mb-2">This order link isn&apos;t valid</h1>
        <p className="text-odisha-black/50 text-sm">
          It may be malformed or reference a product that no longer exists.
        </p>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-4 lg:px-6 py-24 flex flex-col items-center justify-center gap-3 text-odisha-black/40">
      <Loader2 className="w-6 h-6 animate-spin" />
      <p className="text-sm">Loading shared order…</p>
    </div>
  );
}
